version: '3.9'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7.41
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=big_ohlc_service # This schema will create automatically
      - MYSQL_ROOT_PASSWORD=password  # TODO: [Anh Le] cannot use special characters?
    ports:
      - '3306:3306'

  app:
    build: .
    container_name: app
    image: app
    environment:
      MYSQL_URL: 'mysql'
      MYSQL_USER: 'root'
      MYSQL_PASS: 'password'
      MYSQL_SCHEMA: 'big_ohlc_service'
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  integration:
    build:
      context: .
      dockerfile: integration-test/Dockerfile
    container_name: integration
    image: integration
    depends_on:
      - app

volumes:
  mysql-data:
