version: '3.9'
services:

#  mysql:
#    container_name: mysql
#    image: mysql:5.7
#    volumes:
#      - mysql-data:/var/lib/mysql/data
#    environment:
#      MYSQL_URL: '192.168.31.155'
#      MYSQL_USER: 'macuser'
#      MYSQL_PASS: 'macuser'
#      MYSQL_SCHEMA: 'big_ohlc_service'
#    ports:
#      - 3306:3306

  app:
    build: .
    container_name: app
    image: app
    environment:
      MYSQL_URL: '192.168.31.155'
      MYSQL_USER: 'macuser'
      MYSQL_PASS: 'macuser'
      MYSQL_SCHEMA: 'big_ohlc_service'
    ports:
      - 8080:8080
    depends_on:
      - mysql

  integration:
    build:
      context: .
      dockerfile: integration-test/Dockerfile
    container_name: integration
    image: integration
    depends_on:
      - app

volumes:
  mysql-data:
